name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  rehost-image:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull original image
        run: |
          docker pull erev0s/vampi:latest

      - name: Tag image to my repository
        run: |
          docker tag erev0s/vampi:latest arkad29/arkad.repo:latest

      - name: Push image to my repository
        run: |
          docker push arkad29/arkad.repo:latest

